AWSTemplateFormatVersion: "2010-09-09"
Description: This yml file creates the required network and server infrastructure for the Udagram application
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  VPCCidr:
    Description: IP range for the VPC
    Type: String
    Default: 10.0.0.0/16
  PublicSubnet1Cidr:
    Description: IP address range for public subnet 1 in the first AZ
    Type: String
    Default: 10.0.0.0/24
  PublicSubnet2Cidr:
    Description: IP address range for public subnet 2 in the second AZ
    Type: String
    Default: 10.0.0.1/24
  PrivateSubnet1Cidr:
    Description: IP address range for the private subnet 1 in the first AZ
    Type: String
    Default: 10.0.0.2/24
  PrivateSubnet2Cidr:
    Description: IP address range for the private subnet 2 in the second AZ
    Type: String
    Default: 10.0.0.3/24
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
  InternetGatewayVPCAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
