AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Adeniji Charles

Parameters:
  EnvironmentName: 
    Description: An environment name that will be prefixed to all resources name
    Type: String
    Default: UdagramCFProject

Resources:
  # Application load balancer security group
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Load balancer security group
      GroupDescription: Allows http traffic in and out of the load balancer
      VpcId: 
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
